appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JJbx29uJ3jV8zg87fSh6Hd9DFODD6Cb17q/BAb8IxB+UeasG9+ieIG6/ZnMuwan6OkWovoHPRs8l8epwQnKyJR++0oIZyKrXLEoRsUKvqkDUeAm9+DFjf8atE5K0dFYqXadKB/+qWA29JkOHW9Ryevr6q29z7oXbgHT5kLxKWb53d+fTNhPphKR8xN//lxxjVwDzhU1XX0vOFoSjpdCJ9C+joIg79gU4K0K8zwoUqxhju1F02d7Kj5FU4BqeydSpqbHYMuJRor8pizyF7SuXylAuAs0yuoQh3NTZ4ahh1KmMpEBzsR27K89rZNd150bTR6kausQ0loOAn2DGqx4rybTxMzJaqVMw71qDPgkXtON1x1mQdOvZ6pRpuKiToO2WkL6H6gcNJgWYEA3P5ANt2m5lTWz3AhLBE24aVbz4ysBgIAk1Pfosd+hvQ3odG0ePm4J3fhIDsezNHg8tMiYF5wfJ1ReGapCWke3O4z3zFfAzbWl7WG0n6Ah6Fni0gkeBzTWQFY386XIkLu3MwJymU932W9UsJfji/gsL4CZxZ+JfgTgHUpy/d5j1/RZHp5+BfHudPUdSDVjXJXM3WpS5zlJJnc0HMCGWUsr2lWnUFqVRvRJGOxXuttQirP7mMdP64DEWPK1kVc2k0BuuGkfkiOxr9+CEFWB3muIaMVe/DkA=
conda_forge_output_validation: true
