travis:
  secure:
    BINSTAR_TOKEN: bO45nFjJVUY+8t16ZVTMyYRrNJ5igbeS6ly4LcDx8A/xHKXnb8/fTHg/5v6okvzhjTjKiNBenIBY2PY4j7rucLKcmYqvbkTmOZYMKPJTkar+N5doChh32ZXp+x3s8YttbLZ0/DWb8mLe5TVIF1bb8jWGCH8a/z78FYkr+GLH2iU4V8kp0CyYUWuDctzO58qs6O6B5X57zepqR0ko9G1WMJS7lZu37DcwfZP6GZYZ+edpp0QmhltxdjhIEM0BqcBWLvobyt4j7Nsjmhguafsi5fQHiOlk/lPz9Kb7JDvT2GsjFCaIzCLTwzO4AyAj4dyvHllNpgIgOTtSqAnfkankDtLxXyJxScg51dNY53NB6ptkLeojl+bXGrxNHkUaYImQxqVSeJ0Z4szuJ2qs8xxX28GEWBn3nOa7PlrJ5ZF393EwbH4n2RSAlkQVfIl2ebDczMAEr+81wmdTGeFaF4EPX/vX4v2dwjmu2Fq+sX3OGd8u65Kgc6GrsKgOLZx2V50oax9IDfnHmVuLavvZOA+B0RB8O50E1wzUdx87pYHpvM3MplRRbAnJYQwwFIDaxy+U9XiD6RFQ67wUOZptaBd06ukU4c+zDBb0Zc7r4kYgLQcTwHwdEYGVq9PlHXzQRuimleYN8e/xaC40O7W3vmk9bjllxU328OgtOULfI71t6xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
